global:
 scrape_interval: 5s
 evaluation_interval: 5s

remote_write:
#- url: "http://STORAGE_ADAPTER_HOST:STORAGE_ADAPTER_PORT/write"
remote_read:
#- url: "http://STORAGE_ADAPTER_HOST:STORAGE_ADAPTER_PORT/read"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
